spring:
  application:
    name: Core-Server
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crt_portal_new
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: gowtham.ala12345@gmail.com
    password: uygm lawt nzvd qkrg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

springdoc:
  swagger-ui:
    enabled: true
    path: /
  api-docs:
    enabled: true
    path: /api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-token:
    expiration: 604800000

client:
  url: ${CLIENT_URL:http://localhost:3000}

server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
    connection-timeout: 20000
    max-keep-alive-requests: 100
    max-connections: 10000
    accept-count: 100
    threads:
      max: 200
      min-spare: 10
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

