spring:
  application:
    name: Core-Server
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crt_portal_new
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: gowtham.ala12345@gmail.com
    password: uygm lawt nzvd qkrg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

springdoc:
  swagger-ui:
    enabled: true
    path: /
  api-docs:
    enabled: true
    path: /api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-token:
    expiration: 604800000

client:
  url: ${CLIENT_URL:http://localhost:3000}

server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
    connection-timeout: 20000
    max-keep-alive-requests: 100
    max-connections: 10000
    accept-count: 100
    threads:
      max: 200
      min-spare: 10
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Monitoring and Metrics Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops,httptrace,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s
    enable:
      jvm: true
      system: true
      process: true
      hikaricp: true
      jdbc: true
    tags:
      application: crt-portal

# WebSocket Configuration
websocket:
  allowed-origins: 
    - "http://localhost:3000"
    - "http://localhost:3001" 
    - "http://127.0.0.1:3000"
  heartbeat:
    interval: 25000  # 25 seconds
    timeout: 60000   # 60 seconds
